version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: social-media-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: social-media-platform
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - social-media-network

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: social-media-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social-media-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: social-media-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/social-media-platform?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - social-media-network
    volumes:
      - ./uploads:/usr/src/app/uploads

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: social-media-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      REACT_APP_FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - social-media-network

volumes:
  mongodb_data:
  redis_data:

networks:
  social-media-network:
    driver: bridge
